### ISSUE TITLE
Get back into working state

### ISSUE THREAD

**Issue by Squadrick** [Squadrick/shadesmar#12]
bbf9451310f78b8632c46700dc85dddb45d74b05 broke both pubsub and RPC since the change was pretty massive. 

Idiotic of me to not make smaller commits.

**Comment by shrijitsingh99** [comment]
It would be good if there were version tags, such problems can be avoided this way in the future this way.

**Comment by Squadrick** [comment]
@shrijitsingh99 I'm hoping to get `shadesmar` ready for an alpha release after #5, #9 and #14 are closed. I'll start tagging versions after that. 

#5 would be the most challenging, I have a potential design ready and should get the code ready is a week or so. It would be great if you could take a look and review it.
