### ISSUE TITLE
Add tests to CI

### ISSUE THREAD

**Issue by shrijitsingh99** [Squadrick/shadesmar#14]
Having tests as part of the CI would ensure the repo is always in a functional state and fewer bugs creep in.
gtest would be a good fit for this.

**Comment by Squadrick** [comment]
Yeah, I'm currently working on this but with using [Catch2](https://github.com/catchorg/Catch2) instead. ANy reason to pick `gtest` instead? 

The biggest issue with Catch2 is the multiple processes needed for proper testing. Running a `fork()` in the middle of a Catch test seems to not work as expected.

**Comment by Squadrick** [comment]
See the branch `tests`.
