### ISSUE TITLE
just some questions

### ISSUE THREAD

**Issue by amunhoz** [Squadrick/shadesmar#28]
Every instance running shadesmar will share the same events base correct? There is no way to open a different channel like unix sockets?
What about instances running inside containers (docker), will they share the same events base too?

Thanks

**Comment by Squadrick** [comment]
> Every instance running shadesmar will share the same events base correct? There is no way to open a different channel like unix sockets?

I'm not sure what you mean by "events base". But each pubsub stream is defined by a `topic`. Each `topic` acts roughly like a Unix socket.

> What about instances running inside containers (docker), will they share the same events base too?

All processes within the docker container are visible to each other and share topics but are not visible to processes running outside the container.

**Comment by amunhoz** [comment]
> I'm not sure what you mean by "events base". But each pubsub stream is defined by a `topic`. Each `topic` acts roughly like a Unix socket.
As i understanded, every process in the host OS share the same topics.
But dockers will share the topics inside the container only.
Correct?

**Comment by Squadrick** [comment]
> > I'm not sure what you mean by "events base". But each pubsub stream is defined by a `topic`. Each `topic` acts roughly like a Unix socket.
> 
> As i understanded, every process in the host OS share the same topics.
> But dockers will share the topics inside the container only.
> Correct?

Yup.
