### ISSUE TITLE
Question to relation with ros2

### ISSUE THREAD

**Issue by mhubii** [Squadrick/shadesmar#55]
Hi there, I came across this code through reddit.

It is not really an issue, but I also couldnt find a forum. Please feel free to close.

I am wondering what advantages this library offers over ros2 for example.

Thanks and kind regards

**Comment by Squadrick** [comment]
Hi @mhubii, it's fine to create an issue to discuss this.

This library isn't comparable to ROS2. ROS2 is a much more cohesive set of tools, APIs, and libraries for robotics. One part of ROS2 (and ROS) is the ability that allows two processes on the same system to communicate through pubsub or RPCs. ROS2 internally uses a middleware called DDS for this transport (you can read more about it [here](http://design.ros2.org/articles/ros_on_dds.html)), which in turn uses UDP/TCP depending on the implementation. Shadesmar is better compared with DDS. It's just used for transporting messages between processes.

The advantages it has over DDS are simplicity and performance (this is my claim, I have not verified it so take it with a heap of salt). However, DDS is a much more battle-tested and robust framework.

**Comment by mhubii** [comment]
first of all, thanks for the answer. I didn't mean to compare the ecosystem that built around ROS with this library.

ROS in it's core is also just a means of passing data around. It is true, that starting with ROS2, DDS is used for this. While this may differ for the specific DDS (which ROS2 only wraps), from my understanding, most DDSs also operate on shared memory, plus giving you the possibility to communicate via other messaging protocols to different machines. Henceforth the question. I do not agree that DDSs use UCP/TCP by default.

**Comment by Squadrick** [comment]
@mhubii I misinterpreted your question, my bad. You're right, DDS is just a spec and it has been implemented over shared memory.

To answer your original question then:

> I am wondering what advantages this library offers over ros2 for example.

Nothing. ROS2 is better for every use case. Shadesmar is probably easier to understand, it is definitely fewer LoCs.

**Comment by mhubii** [comment]
thanks @Squadrick, it also appears very light weight, which is nice
