### ISSUE TITLE
 Memory alignment 

### ISSUE THREAD

**Issue by m1018** [Squadrick/shadesmar#59]
Hello, what are the considerations for the implementation of memory alignment in the code? Hope you can understand, thank you

**Comment by Squadrick** [comment]
All the memory management (allocation, deallocation and copying) is done using a [`Copier`](https://github.com/Squadrick/shadesmar/blob/master/include/shadesmar/memory/copier.h) interface, with the default implementation using `malloc`, `free` and `memcpy`, so no special aligned memory.

You can implement your own `Copier` which can handle custom aligned memory, and pass that to the library instead.
