### ISSUE TITLE
cannot complie lib on windows and linux platform with CMakeLists.txt

### ISSUE THREAD

**Issue by SccotMu** [Squadrick/shadesmar#62]
here is the errors log in windows :

**CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "Findbenchmark.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "benchmark", but CMake did not find one.

  Could not find a package configuration file provided by "benchmark" with
  any of the following names:

    benchmarkConfig.cmake
    benchmark-config.cmake

  Add the installation prefix of "benchmark" to CMAKE_PREFIX_PATH or set
  "benchmark_DIR" to a directory containing one of the above files.  If
  "benchmark" provides a separate development package or SDK, be sure it has
  been installed.**

**Comment by tan-wei** [comment]
Install benchmark firstly. I think on Windows, you could try `vcpkg install benchmark`.

**Comment by zeroRains** [comment]
How to handle this case in ubuntu 20.04?
