### ISSUE TITLE
Switch from cmake to bazel 

### ISSUE THREAD

**Issue by Squadrick** [Squadrick/shadesmar#9]

**Comment by sudo-panda** [comment]
I would like to work on this issue.

**Comment by Squadrick** [comment]
@sudo-panda Thanks, looking forward to the PR. Let me know if you need any help.

**Comment by Squadrick** [comment]
Use bazel as the source of truth, and use [bazel-to-cmake](https://github.com/google/bazel-to-cmake) in a GitHub job to do the conversion.
